ask for backend plugin

diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -68,4 +68,50 @@ ask() {
     echo $ANSWER
 }
 
+choice() {
+    local MESSAGE="$1"
+    local DEFAULT="$2"; shift 2
+    local OPTIONS=("$@")
+    local DEFAULT_OPTION=
+    local ANSWER=
+    local CHOICE=
+
+    stderr "$MESSAGE"
+    for OPTION in "${!OPTIONS[@]}"; do
+        if [ "$DEFAULT" == "${OPTIONS[OPTION]}" ]; then
+            DEFAULT_OPTION="$OPTION"
+        fi
+        stderr " $OPTION) ${OPTIONS[OPTION]}"$([ "$DEFAULT" == "${OPTIONS[OPTION]}" ] && echo ' (by default)')
+    done
+
+    while read -r -p "${PS3:=#?}" ANSWER; do
+        if  [[ "$ANSWER" == "" ]]; then
+            if ! [[ "${DEFAULT_OPTION+isset}" ]]; then
+                continue
+            fi
+            ANSWER="$DEFAULT_OPTION"
+        fi
+
+        if ! in_array "$ANSWER" "${!OPTIONS[@]}"; then
+            warn "Invalid option: $ANSWER ${!OPTIONS[ANSWER]}"
+            continue
+        fi
+        break;
+    done
+
+    echo "${OPTIONS[ANSWER]}"
+}
+
+in_array() {
+	local NEEDLE="$1"; shift
+	local HAYSTACK=("$@")
+	for ITEM in "${HAYSTACK[@]}"; do
+		if [[ "$ITEM" == "$NEEDLE" ]]; then
+			return 0
+		fi
+	done
+
+	return 1
+}
+
 library_init
